//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hist_mmorpg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hist_mmorpg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skill,skill_1,Command,effStart,battle,0.4,siege,0.4,npcHire,0.2,effEnd
        ///skill,skill_2,Chivalry,effStart,famExpense,0.2,fiefExpense,0.1,fiefLoy,0.1,npcHire,0.1,siege,0.1,effEnd
        ///skill,skill_3,Abrasiveness,effStart,battle,0.15,death,0.05,fiefExpense,-0.05,famExpense,0.05,time,0.05,siege,-0.1,effEnd
        ///skill,skill_4,Accountancy,effStart,time,0.1,fiefExpense,-0.2,famExpense,-0.02,fiefLoy,-0.05,effEnd
        ///skill,skill_5,Stupidity,effStart,battle,-0.4,death,0.05,fiefExpense,0.02,famExpense,0.2,fiefLoy,-0.1,npcHire,-0.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gameObjects {
            get {
                return ResourceManager.GetString("gameObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dimensions,27,18
        ///,,,,SHI01,,,,,,,,,,,,,
        ///,,,,,,,,,,,,,,,,,
        ///,,,,,SLO01,,,,,,,,,,,,
        ///,,,,,,,,,ENU01,,,,,,,,
        ///,,,,,,,SMA01,,ENU03,ENU02,,,,,,,
        ///,,,,,,,,ENU06,ENU05,ENU04,,,,,,,
        ///,,,,,,,ECU02,ECU01,EDU02,EDU01,,,,,,,
        ///,,,,,,ECU05,ECU04,ECU03,EDU05,EDU04,EDU03,,,,,,
        ///,,,,,,,ELA01,ECU07,ECU06,EYS03,EYS02,EYS01,,,,,
        ///,,,,,EMN01,,ELA03,ELA02,EYS07,EYS06,EYS05,EYS04,,,,,
        ///,,,,,,,,ELA05,ELA04,EYS11,EYS10,EYS09,EYS08,,,,
        ///,,,,,,,ELA07,ELA06,EYS16,EYS15,EYS14,EYS13,EYS12,,,,
        ///,,,,,,,,ELA09,ELA08,EYS19,EYS18,EYS17,,,, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
    }
}
